PierresTreats/Models/Treat.cs
using System.Collections.Generic;

namespace PierresTreats.Models
{
    public class Treat
    {
        public int TreatID {get; set;}
        public string Name {get; set;}
        public virtual ApplicationUser User {get; set;}
        public ICollection<FlavorTreat> Flavors {get;}
        public Treat()
        {
            this.Flavors = new HashSet<FlavorTreat>();
        }
    }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
    
    public class TreatsController : Controller
    {
        private readonly PierresTreatsContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public ActionResult Index()
        {
            List<Treat> model = _db.Treats.Include(treats => treats.Flavors).OrderBy(s => s.Name).ToList();

            return View(model);

        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.FlavorID = new SelectList(_db.Flavors, "FlavorID", "Description");
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(Treat treat, int FlavorID)
        {
            var userID = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userID);
            treat.User = currentUser;
            _db.Treats.Add(treat);
            if(FlavorID != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat() {FlavorID = FlavorID, TreatID = treat.TreatID});
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisTreat = _db.Treats.Include(treat => treat.Flavors).ThenInclude(join => join.Flavor).FirstOrDefault(treat => treat.TreatID == id);
            return View(thisTreat);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatID == id);
            ViewBag.FlavorID = new SelectList(_db.Flavors, "FlavorID", "Description");
            return View(thisTreat);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Treat treat, int FlavorID)
        {
            if(FlavorID != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat() {FlavorID = FlavorID, TreatID = treat.TreatID});
            }
            _db.Entry(treat).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AddFlavor(int id)
        {
            var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatID == id);
            ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorID", "Description");
            return View(thisTreat);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddFlavor(Treat treat, int FlavorID)
        {
            if (FlavorID != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat() { FlavorID = FlavorID, TreatID = treat.TreatID });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatID == id);
            return View(thisTreat);
        }


        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisTreat = _db.Treats.FirstOrDefault(treats =>treats.TreatID == id);
            _db.Treats.Remove(thisTreat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult DeleteFlavor(int joinID)
        {
            var joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatID == joinID);
            _db.FlavorTreats.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@model PierresTreats.Models.Treat;

<h2>Add a Flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    <div class="well">
        @Html.HiddenFor(model => model.TreatID)

        @Html.Label("Select Flavor")
        @Html.DropDownList("FlavorID")

        <input type="submit" value="Save"  class="btn"/>
    </div>
}

PierresTreats/Views/Treats/Create.cshtml
@model PierresTreats.Models.Treat

<h4>Add a new treat</h4>

@using (Html.BeginForm())
{
    <div class="well">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)<br>

        @Html.Label("Select Flavor")
        @Html.DropDownList("FlavorID")<br>

        <input type="submit" value="Add new treat" class="btn" />
    </div>
}

PierresTreats/Views/Treats/Delete.cshtml
@model PierresTreats.Models.Treat

<h2>Are you sure you want to delete this treat?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete"  class="btn"/>
}

PierresTreats/Views/Treats/Details.cshtml
@model PierresTreats.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.Flavors.Count == 0)
{
  <p>This treat is not associated with any flavors yet.</p>
}
else
{
  <h4>This treat contains these flavors:</h4>
  <ul>
  @foreach(var join in Model.Flavors)
  {
    <li>@join.Flavor.Description</li>
    @using (Html.BeginForm("DeleteFlavor", "Treats"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatID)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<button class="btn">@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatID })</button>
<button class="btn">@Html.ActionLink("Edit treat", "Edit", new { id = Model.TreatID })</button>
<button class="btn">@Html.ActionLink("Delete treat", "Delete", new { id = Model.TreatID })</button>

PierresTreats/Views/Treats/Edit.cshtml
@model PierresTreats.Models.Treat

<h2>Edit</h2>
<h4>Edit this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    <div class="well">
        @Html.HiddenFor(model => model.TreatID)
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
        @Html.LabelFor(model => model.Flavors)
        @Html.DropDownList("FlavorID")

        <input type="submit" value="Save"  class="btn"/>
    </div>
}

PierresTreats/Views/Treats/Index.cshtml
@using PierresTreats.Models;
@model List<PierresTreats.Models.Treat>;

<h1>Treats</h1>

@if (@Model.Count == 0)
{
    <h3>No treats have been added yet!</h3>
} 

@foreach (Treat treat in Model)
{
    <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatID })</li>
}