PierresTreats/Models/Flavor.cs
using System.Collections.Generic;

namespace PierresTreats.Models
{
    public class Flavor
    {
        public int FlavorID {get; set;}
        public string Description {get; set;}
        public virtual ICollection<FlavorTreat> Treats {get; set;}
        public Flavor()
        {
            this.Treats = new HashSet<FlavorTreat>();
        }
    }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PierresTreats.Controllers
{
    public class FlavorsController : Controller
    {
        private readonly PierresTreatsContext _db;
        public FlavorsController(PierresTreatsContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Flavor> model = _db.Flavors.ToList();
            return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Flavor flavor)
        {
            _db.Flavors.Add(flavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisFlavor = _db.Flavors.Include(flavor => flavor.Treats).ThenInclude(join => join.Treat).FirstOrDefault(flavor => flavor.FlavorID == id);
            return View(thisFlavor);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
             var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorID == id);
             return View(thisFlavor);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Flavor flavor)
        {
            _db.Entry(flavor).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        [Authorize]
        public ActionResult AddTreat(int id)
        {
            var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorID == id);
            ViewBag.TreatID = new SelectList(_db.Treats, "TreatID", "Name");
            return View(thisFlavor);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddTreat(Flavor flavor, int TreatID)
        {
            if (TreatID != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat() { TreatID = TreatID, FlavorID = flavor.FlavorID });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorID == id);
            return View(thisFlavor);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorID == id);
            _db.Flavors.Remove(thisFlavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult DeleteTreat(int joinID)
        {
            var joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatID == joinID);
            _db.FlavorTreats.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

PierresTreats/Views/Flavors/AddTreat.cshtml
@model PierresTreats.Models.Flavor;

<h2>Add a Treat</h2>

<h4>Add a treat to this flavor: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    <div class="well">
        @Html.HiddenFor(model => model.FlavorID)

        @Html.Label("Select Treat")
        @Html.DropDownList("TreatID")

        <input type="submit" value="Save"  class="btn"/>
    </div>
}

PierresTreats/Views/Flavors/Create.cshtml
@model PierresTreats.Models.Flavor

<h4>Add a new flavor</h4>
@using (Html.BeginForm())
{   
    <div class="well">
        @Html.LabelFor(model => model.Description)
        @Html.TextBoxFor(model => model.Description)<br>
        <input type="submit" value="Add new flavor" class="btn"/>
    </div>
}

PierresTreats/Views/Flavors/Delete.cshtml
@model PierresTreats.Models.Flavor

<h2>Are you sure you want to delete this flavor?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn" />
}

PierresTreats/Views/Flavors/Details.cshtml
@model PierresTreats.Models.Flavor;

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

@if(@Model.Treats.Count == 0)
{
  <p>This flavor is not associated with any treats yet.</p>
}
else
{
  <h4>Treats known for this flavor:</h4>
  <ul>
  @foreach(var join in Model.Treats)
  {
    <li>@join.Treat.Name</li>

    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatID)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<button class="btn">@Html.ActionLink("Add a treat", "AddTreat", new { id = Model.FlavorID })</button>
<button class="btn">@Html.ActionLink("Edit flavor", "Edit", new { id = Model.FlavorID })</button>
<button class="btn">@Html.ActionLink("Delete flavor", "Delete", new { id = Model.FlavorID })</button>

PierresTreats/Views/Flavors/Edit.cshtml
@model PierresTreats.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    <div class="well">
        @Html.HiddenFor(model => model.FlavorID)

        @Html.LabelFor(model => model.Description)
        @Html.EditorFor(model => model.Description)

        <input type="submit" value="Save"  class="btn"/>
    </div>
}

PierresTreats/Views/Flavors/Index.cshtml
@using PierresTreats.Models;
@model List<PierresTreats.Models.Flavor>;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 

@foreach (Flavor flavor in Model)
{
  <li>@Html.ActionLink($"{flavor.Description}", "Details", new { id = flavor.FlavorID })</li>
}